library/routes/routes.py
from flask import render_template, Blueprint, request, flash, abort, redirect, url_for
from flask_login import login_required, current_user

from ..db.forms import ContactForm, EditProfile, BookApp
from ..db.models import Profile, Specializations, Appointment, User
from ..db.db import db

from ..valid import calculate_age

import os
from dotenv import load_dotenv

import smtplib

load_dotenv()
EMAIL_TO = os.getenv("EMAIL_TO")
EMAIL_FROM = os.getenv("EMAIL_FROM")
SMTP = os.environ.get("SMTP")
PASSWORD = os.getenv("PASSWORD")


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


@pages.route("/", methods=["GET", "POST"])
def home():
    if request.method == "GET":
        booked_app = []
        appointment = []

        if current_user.is_authenticated:
            if current_user.isDoctor:
                appointment = Appointment.query.filter_by(
                    doctor_id=current_user._id
                ).all()

            elif current_user.isPatient:
                booked_app = Appointment.query.filter_by(
                    patient_id=current_user._id
                ).all()

        doctor_profiles = {}
        for app in appointment:
            doctor_profile = Profile.query.filter_by(userid=app.doctor_id).first()
            doctor_profiles[app.doctor_id] = doctor_profile

        if current_user.is_authenticated:
            display = Appointment.query.filter_by(patient_id=current_user._id).all()

            display_doctor = []
            for appointment in display:
                if appointment.doctor_id:
                    doctor_profile = Profile.query.filter_by(
                        userid=appointment.doctor_id
                    ).first()
                    display_doctor.append(doctor_profile)
                else:
                    display_doctor.append(None)

                return render_template(
                    "main/home.html",
                    booked_app=booked_app,
                    appointment=appointment,
                    doctor_profiles=doctor_profiles,
                    doctor_profile=doctor_profile,
                )

        else:
            display = []
            display_doctor = []

        return render_template(
            "main/home.html",
            booked_app=booked_app,
            appointment=appointment,
            doctor_profiles=doctor_profiles,
        )

    return render_template("main/home.html")


@pages.route("/appointment", methods=["GET", "POST"])
@login_required
def appointment():
    if request.method == "GET":
        specs = Specializations.query.all()
        return render_template("main/appointment.html", specs=specs)

    elif request.method == "POST":
        selected_specialization = request.form.get("specs")
        specs_id = Specializations.query.filter_by(
            specialization=selected_specialization
        ).first()

        if specs_id:
            appointments = (
                Appointment.query.join(User, Appointment.doctor_id == User._id)
                .filter(User.specs_id == specs_id._id, Appointment.availability == True)
                .all()
            )
        else:
            appointments = []

        return render_template(
            "main/appointment.html",
            specs=Specializations.query.all(),
            appointment=appointments,
            selected_specialization=selected_specialization,
        )


@pages.route("/app_details/<int:app_id>", methods=["GET", "POST"])
@login_required
def app_details(app_id: int):
    appointment = Appointment.query.filter_by(app_id=app_id).first()
    form = BookApp()

    if appointment.profile and appointment.profile.birthdate:
        patient_birthdate = appointment.profile.birthdate
        gender = appointment.profile.gender
    else:
        patient_birthdate = None
        gender = None

    if appointment.patient_id:
        age, month = calculate_age(patient_birthdate)
    else:
        age, month = None, None

    if not appointment:
        flash("Appointment not found.", "danger")
        return redirect(url_for("pages.appointment"))

    if request.method == "POST":
        if appointment.availability:
            appointment.availability = False
            appointment.patient_id = current_user._id
            db.session.commit()
            flash("Appointment booked successfully!", "success")
            return redirect(url_for("pages.app_details", app_id=app_id))

        appointment = Appointment.query.get_or_404(app_id)

        if appointment.doctor_id != current_user._id:
            flash("You are not authorized to submit recommendations.", "danger")
            return redirect(url_for("pages.app_details", app_id=app_id))

        recommendations = request.form.get("recommendations")
        appointment.recommendations = recommendations
        db.session.commit()

        flash("Recommendations submitted successfully!", "success")
        return redirect(
            url_for("pages.app_details", app_id=app_id, appointment=appointment)
        )

    if appointment.doctor_id:
        doctor_profile = Profile.query.filter_by(userid=appointment.doctor_id).first()
        user = User.query.get(appointment.doctor_id)
        if user:
            specialization = Specializations.query.get(user.specs_id)
        else:
            specialization = None
    else:
        doctor_profile = None

    return render_template(
        "main/app_details.html",
        appointment=appointment,
        form=form,
        doctor_profile=doctor_profile,
        specialization=specialization,
        age=age,
        month=month,
        gender=gender,
    )


@pages.route("/profile/<int:_id>", methods=["GET", "POST"])
@login_required
def profile(_id: int):
    if request.method == "GET":
        profile_data = Profile.query.filter_by(userid=_id).first()

        if not profile_data:
            abort(404)

        if not current_user.isAdmin:
            if current_user._id != _id:
                abort(403)

        return render_template("user/profile.html", profile_data=profile_data)


@pages.route("/edit_profile/<int:_id>", methods=["GET", "POST"])
@login_required
def edit_profile(_id: int):
    profile_data = Profile.query.filter_by(userid=_id).first()
    form = EditProfile(obj=profile_data)

    if current_user._id != _id:
        abort(403)

    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(profile_data)
        db.session.commit()
        flash("Profile updated successfully!", "success")
        return redirect(url_for("pages.profile", _id=_id))

    return render_template(
        "user/edit_profile.html", profile_data=profile_data, form=form
    )


@pages.route("/about")
def about():
    return render_template("main/about.html")


@pages.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()

    if request.method == "POST":
        if form.validate() == False:
            flash("All fields are required.")
            return render_template("main/contact.html", form=form)
        else:
            recipient = EMAIL_TO
            subject = form.subject.data
            sender = EMAIL_FROM
            message = f"""
            FROM: {form.name.data} <{form.email.data}>
            {form.body.data}
            """

            email_message = (
                f"Subject: {subject}\nFrom: {sender}\nTo: {recipient}\n\n{message}"
            )

            try:
                with smtplib.SMTP(SMTP, 587) as server:
                    server.starttls()
                    server.login(EMAIL_FROM, PASSWORD)
                    server.sendmail(sender, recipient, email_message)
                    server.close()
            except:
                print("-" * 30)
                print(email_message)
                print("-" * 30)

            return render_template("main/contact.html", success=True)
    elif request.method == "GET":
        return render_template("main/contact.html", form=form)


@pages.route("/deleteapp/<int:app_id>")
@login_required
def delete_app(app_id):
    appointment = Appointment.query.get_or_404(app_id)
    db.session.delete(appointment)
    db.session.commit()
    flash("Appointment deleted successfully.", "success")
    return redirect(request.referrer)  # redirects to current page


@pages.route("/deleteapp2/<int:app_id>")
@login_required
def delete_app_patient(app_id):
    appointment = Appointment.query.get_or_404(app_id)
    if appointment.patient_id == current_user._id:
        appointment.patient_id = None
        appointment.availability = True
        db.session.commit()
    flash("Appointment deleted successfully.", "success")
    return redirect(request.referrer)

library/templates/add_user.html
{% extends 'layout.html' %}

{% block head_content%}
<title> Admin </title>
{% endblock %}

{% block main_content %}

<h3> Admin Panel </h3>

{% for message in get_flashed_messages() %}
<div class="flash"> <svg class="octicon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
        <path fill-rule="evenodd"
            d="M4.47.22A.75.75 0 015 0h6a.75.75 0 01.53.22l4.25 4.25c.141.14.22.331.22.53v6a.75.75 0 01-.22.53l-4.25 4.25A.75.75 0 0111 16H5a.75.75 0 01-.53-.22L.22 11.53A.75.75 0 010 11V5a.75.75 0 01.22-.53L4.47.22zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5H5.31zM8 4a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 018 4zm0 8a1 1 0 100-2 1 1 0 000 2z">
        </path>
    </svg>
    {{ message }} </div>
{% endfor %}

{% if current_user.isAdmin %}
<h4>Create new user</h4>
<form method="post" action="{{ url_for('pages.add_user')}}">
   
    <div class="form-group">
        {{ form.email.label }} {{ form.email(class="form-control") }}
    </div>
    
    <div class="form-group">
        {{ form.password.label }} {{ form.password(class="form-control") }}
    </div>
    
    <div class="form-group">
        {{ form.confirm_password.label }} {{ form.confirm_password(class="form-control") }}
    </div>

    <div class="form-group">
        {{ form.isAdmin.label }} {{ form.isAdmin(class="form-control") }}
    </div>

    <div class="form-group">
        {{ form.isDoctor.label }} {{ form.isDoctor(class="form-control") }}
    </div>

    <div class="form-group">
        {{ form.isPatient.label }} {{ form.isPatient(class="form-control") }}
    </div>

    <div class="form-group">
        {{ form.isActive.label }} {{ form.isActive(class="form-control") }}
    </div>

    <div class="form-group">
        {{ form.submit(class="btn btn-primary btn-block mb-3") }}
    </div>
</form>





{% else %}
<p>You do not have permission to access the Admin Panel.</p>
{% endif %}



{% endblock %}

library/templates/analytics.html
{% extends 'layout.html' %}

{% block head_content%}
<title> Admin </title>
{% endblock %}

{% block main_content %}

<h3> Admin Panel </h3>

{% if current_user.isAdmin %}

<p>Total number of users: {{ total_users }}</p>
<p>Total number of doctors: {{ doctors_count }}</p>
<p>Total number of appointments: {{ appointments_count }}</p>

<canvas id="popularity" style="width:100%;max-width:600px"></canvas>

{% else %}
<p>You do not have permission to access the Admin Panel.</p>
{% endif %}

{% endblock %}

library/templates/app_details.html
{% extends 'layout.html' %}

{% block head_content%}

{% endblock %}

{% block main_content %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-primary" role="alert">
  {% for message in messages %}
  {{ message }}
  {% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="appointment_container">
  <h2>Appointment Details</h2>
  {% if current_user.isDoctor %}

  <dl>
    <dt>Date</dt>
    <dd>{{ appointment.app_date }}</dd>
    <dt>Time</dt>
    <dd>{{ appointment.app_time }}</dd>

    <dt>Patient</dt>
    {% if appointment.patient_id %}
    <td>{{ appointment.profile.name }}</td>
    <td>{{ appointment.profile.surname }}</td>
    {% else %}
    <dd>Patient information not available</dd>
    {% endif %}
  </dl>

  <div class="container">
    <section class="mt-4" style="text-align: center;">
      <h4>Recommendations</h4>
      {% if appointment.recommendations %}
      <div class="recommendations">
        <p>{{ appointment.recommendations }}</p>
      </div>
      {% else %}
      <form action="{{ url_for('pages.app_details', app_id=appointment.app_id) }}" method="post">
        <div class="form-group">
          <label for="recommendations">Add Recommendations:</label>
          <textarea class="form-control" id="recommendations" name="recommendations" rows="4"
            style="width: 50%; margin: 0 auto;"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </section>
    {% endif%}
  </div>


  {% else %}

  <dl>
    <dt>Date</dt>
    <dd>{{ appointment.app_date }}</dd>
    <dt>Time</dt>
    <dd>{{ appointment.app_time }}</dd>

    {% if appointment.doctor_id %}
    <dt>Specialization</dt>
    {% if specialization %}
    <dd>{{ specialization.specialization }}</dd>
    {% else %}
    <dd>Specialization information not available</dd>
    {% endif %}

    <dt>Doctor</dt>
    {% if doctor_profile %}
    <dd>{{ doctor_profile.name }} {{ doctor_profile.surname }}</dd>
    {% else %}
    <dd>Doctor information not available</dd>
    {% endif %}

    {% if not appointment.availability %}

    <h4>Recommendations</h4>
    {% if appointment.recommendations %}
    <div class="recommendations">
      <p>{{ appointment.recommendations }}</p>
    </div>
    {% else %}
    <p> Currently, there are no recommendations available.</p>
    {% endif %}
    {% endif %}

  </dl>
  {% if appointment.availability %}
  <form method="post" action="{{ url_for('pages.app_details', app_id=appointment.app_id) }}">
    {{ form.hidden_tag() }}
    <button type="submit" class="btn btn-primary">Book Appointment</button>
  </form>
  {% endif %}
  {% endif %}
  {% endif %}

</div>
{% endblock %}

library/templates/ava_users.html
{% extends 'layout.html' %}

{% block head_content%}
<title> Admin </title>
{% endblock %}

{% block main_content %}

<h3> Admin Panel </h3>

{% for message in get_flashed_messages() %}
<div class="flash"> <svg class="octicon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
        <path fill-rule="evenodd"
            d="M4.47.22A.75.75 0 015 0h6a.75.75 0 01.53.22l4.25 4.25c.141.14.22.331.22.53v6a.75.75 0 01-.22.53l-4.25 4.25A.75.75 0 0111 16H5a.75.75 0 01-.53-.22L.22 11.53A.75.75 0 010 11V5a.75.75 0 01.22-.53L4.47.22zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5H5.31zM8 4a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 018 4zm0 8a1 1 0 100-2 1 1 0 000 2z">
        </path>
    </svg>
    {{ message }} </div>
{% endfor %}

{% if current_user.isAdmin %}

<h4>Add new user:</h4>
<a href="{{ url_for('pages.add_user') }}" class="btn btn-primary bg-success"><i class="fas fa-user-plus"></i></a>
<br>
<h4>Available Users:</h4>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Admin</th>
            <th>Doctor</th>
            <th>Patient</th>
            <th>Active</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user._id }}</td>
            <td>{{ user.email }}</td>
            <td>{{ "Yes" if user.isAdmin else "No" }}</td>
            <td>{{ "Yes" if user.isDoctor else "No" }}</td>
            <td>{{ "Yes" if user.isPatient else "No" }}</td>
            <td>{{ "Yes" if user.isActive else "No" }}</td>
            <td><a href="{{ url_for('pages.edit_user', _id=user._id) }}" class="btn btn-primary"><i
                        class="fas fa-pencil-alt"></i></a></td>
            <td><a href="{{ url_for('pages.delete_user', _id=user._id) }}" class="btn btn-danger"><i
                        class="fas fa-trash-alt"></i></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
<p>You do not have permission to access the Admin Panel.</p>
{% endif %}



{% endblock %}

library/templates/content.html
{% extends 'layout.html' %}

{% block head_content%}
<title> Admin </title>
{% endblock %}

{% block main_content %}

<h3> Admin Panel </h3>

{% if current_user.isAdmin %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-primary" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<h4> Add new specialization </h4>
<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.specialization }}
    {{ form.submit }}
</form>
<br>
<h4> Existing Specializations </h4>
<table class="table">
    <thead>
        <tr>
            <th> Specialization </th>
            <th> Delete </th>
        </tr>
    </thead>
    <tbody>
        {% for spec in specializations %}
        <tr>
            <td> {{ spec.specialization }} </td>
            <td> <a href="{{ url_for('pages.delete_spec', spec_id=spec._id) }}" class="btn btn-danger"><i
                        class="fas fa-trash-alt"></i></a> </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h4> Existing Appointments </h4>
<table class="table">
    <thead>
        <tr>
            <th> Appointment Date</th>
            <th> Appointment Time</th>
            <th> Doctors name</th>
            <th> Doctors surname</th>
            <th> Patient name </th>
            <th> Patient surname</th>
            <th> Availability</th>
            <th> Delete </th>
        </tr>
    </thead>
    <tbody>
        {% for app in appointments %}
        <tr>
            <td> {{ app.app_date }} </td>
            <td> {{ app.app_time }} </td>
            {% if doctor_profile %}
            <td>{{ doctor_profile.name }}</td>
            <td>{{ doctor_profile.surname }}</td>
            {% else %}
            <td>N/A</td>
            <td>N/A</td>
            {% endif %}
            {% if app.patient_id %}
            <td>{{ app.profile.name }}</td>
            <td>{{ app.profile.surname }}</td>
            {% else %}
            <td>N/A</td>
            <td>N/A</td>
            {% endif %}
            <td>{{ "Available" if app.availability else "Booked" }}</td>
            <td> <a href="{{ url_for('pages.delete_app', app_id=app.app_id) }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a> </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
<p>You do not have permission to access the Admin Panel.</p>
{% endif %}

{% endblock %}

library/templates/create_app.html
{% extends 'layout.html' %}

{% block head_content%}

{% endblock %}

{% block main_content %}


<h3> Doctors, please create empty appointment slots </h3>

<form method="post" action="{{ url_for('pages.create_app') }}">  
    <label for="selected_date">Appointment Date:</label>
    <input type="date" id="selected_date" name="selected_date" required>
    <br>
    <label for="selected_time">Appointment Time:</label>
    <input type="time" id="selected_time" name="selected_time" required>
    <br>
    <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="flash-messages">
    {% for message in messages %}
    <div class="flash-message">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

{% endblock %}

library/templates/edit_profile.html
{% extends 'layout.html' %}

{% block head_content %}

{% endblock %}

{% block main_content %}

{% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field, errors in form.errors.items() %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% for message in get_flashed_messages() %}
    <div class="flash">   <svg class="octicon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M4.47.22A.75.75 0 015 0h6a.75.75 0 01.53.22l4.25 4.25c.141.14.22.331.22.53v6a.75.75 0 01-.22.53l-4.25 4.25A.75.75 0 0111 16H5a.75.75 0 01-.53-.22L.22 11.53A.75.75 0 010 11V5a.75.75 0 01.22-.53L4.47.22zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5H5.31zM8 4a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 018 4zm0 8a1 1 0 100-2 1 1 0 000 2z"></path></svg>
        {{ message }} </div>
{% endfor %}

<h4> Edit profile</h4>

<form method="post" name="editprofile" action="{{ url_for('pages.edit_profile', _id=profile_data._id)}}">
    {{ form.hidden_tag() }}
    <dl>
        <dt>Name</dt>
        <dd> {{ form.name(class="formclass") }}</dd>
        <dt>Surname</dt>
        <dd> {{ form.surname(class="formclass") }}</dd>
        <dt>Birthdate</dt>
        <dd>{{ form.birthdate(id="birthdate", class="formclass") }}</dd>
        <dt>Email</dt>
        <dd><input type="text" name="email" value="{{ form.email.data }}" readonly></dd>
        <dt>Telephone</dt>
        <dd>{{ form.telephone(class="formclass") }}</dd>
    </dl>
    {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}

library/templates/edit_user.html
{% extends 'layout.html' %}

{% block head_content %}

{% endblock %}

{% block main_content %}



<h4> Edit User</h4>

<form method="post" name="edituser" action="{{ url_for('pages.edit_user', _id=user._id) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.email.label }} {{ form.email(class="form-control") }}
    </div>
    <div class="form-check">
        {{ form.isAdmin.label }} {{ form.isAdmin(class="form-check-input") }}
    </div>
    <div class="form-check">
        {{ form.isDoctor.label }} {{ form.isDoctor(class="form-check-input") }}
    </div>
    <div class="form-check">
        {{ form.isPatient.label }} {{ form.isPatient(class="form-check-input") }}
    </div>
    <div class="form-check">
        {{ form.isActive.label }} {{ form.isActive(class="form-check-input") }}
    </div>
    <br>
    {% if form.isDoctor.data %}
    <div class="form-group">
        {{ form.specialization.label }} {{ form.specialization(class="form-control") }}
    </div>
    {% endif %}

    <input type="submit" value="Update" class="btn btn-primary">
</form>
{% endblock %}

library/templates/layout.html
{% from "macros/nav.html" import navbar %}
{% from "macros/footer.html" import footer %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MedCorp, Inc.</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="icon" href="static/svg/favicon.png" type="image/x-icon">

    {% block head_content %} {% endblock %}

</head>

<body>
   
    <div class="navbar-nav">
        {{ navbar(current_user) }}
    </div>


    <main>
        <div id="page-container">
            <div id="content-wrap">
                <div class="container col-6">
                
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div  class="alert alert-primary" role="alert">
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                </div>
                {% endif %}
                {% endwith %}
                {% block main_content %} {% endblock %}
            </div>
        </div>
    </div>
    </main>
    <div id="footer">
    {{ footer() }}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

</body>

</html>