library/auth.py
from flask import Flask, render_template, Blueprint, request, session, flash, redirect, url_for, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from forms import LoginForm, RegisterForm
from models import User
from flask_login import login_user, login_required, logout_user
from datetime import datetime
from db import db
from valid import isProperMail

authorize = Blueprint(
    "authorize", __name__, template_folder="templates", static_folder="static"
)

@authorize.route("/login", methods=["GET"])
def login():
    form = LoginForm()
    return render_template("login.html", form=form)

@authorize.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = User.query.filter_by(email=email).first()
    session["logged_in"] = True
    
    if not user or not check_password_hash(user.password, password):
        flash("Email or password is not correct.")
        return redirect(url_for("authorize.login"))
    
    login_user(user, remember=remember)

    return redirect(url_for("pages.home"))

@authorize.route("/register", methods=["GET"])
def register():
    form = RegisterForm()
    return render_template("register.html", form=form)

@authorize.route("/register", methods=["POST"])
def register_post():
    email = request.form.get("email")
    password = request.form.get("password")
    confirm_password = request.form.get("confirm_password")
    isAdmin = False
    isDoctor = False
    isPatient = True
    isActive = True

    user = User.query.filter_by(email=email).first()

    if user:
        flash("User already exists.")
        return redirect("authorize.login")
    
    if not isProperMail(email):
        flash("Please provide correct email address.")
        return redirect("authorize.login")

    if password != confirm_password:
        flash("Passwords are not matching.")
        return render_template("register.html")

    new_user = User(email=email, password=generate_password_hash(password, method='sha256'), isAdmin=isAdmin, isDoctor=isDoctor, isPatient=isPatient, isActive=isActive)

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for("authorize.login"))

@authorize.route("/logout")
@login_required
def logout():
    logout_user()
    session.clear()
    return render_template("home.html")

library/templates/macros/footer.html
{% macro footer() %}

<footer class="bg-dark text-center text-white">
    <small>
        <div class="container p-4 pb-0">
            <section class="mb-4">

            </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            <nav>
                <p>Copyright &copy; 2023. MedCorp, Inc. All rights reserved.</p>
                <a class="text-white" href="/contact">Contact us</a>
                <a class="text-white" href="#top">Back to top</a>
            </nav>
        </div>

    </small>
</footer>

{% endmacro %}

library/templates/macros/nav.html
{% macro navbar(current_user) %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <div class="col-md-2">
            <div class="navbar-nav">
                <a class="nav-item nav-link {% if request.endpoint == 'pages.home' %}active{% endif %}"
                    href="/">Home</a>
                <a class="nav-item nav-link {% if request.endpoint == 'pages.about' %}active{% endif %}"
                    href="/about">About</a>
                <a class="nav-item nav-link {% if request.endpoint == 'pages.contact' %}active{% endif %}"
                    href="/contact">Contact</a>
            </div>
        </div>

        <a href="/" class="col-md-7" id="nav-logo">
            <div class="col-md-7">
                <div class="logo-image">
                    <img src="/static/svg/hospital.png" alt="Logo" class="logo" height="70px" width="70px" />
                </div>
                <div class="logo-word">
                    <h1 class="brand-name"> MedCorp, Inc. </h1>
                </div>
            </div>
        </a>

        <div>
            <div>
                {% if session["logged_in"] == True %}
                <div class="navbar-nav ml-auto">
                    {% if current_user.isAdmin %}
                    <a class="nav-item nav-link {% if request.endpoint == 'pages.admin_panel' %}active{% endif %}"
                        style="text-align:right;" href="/adminpanel">Admin Panel</a>
                    {% endif %}
                    <a class="nav-item nav-link {% if request.endpoint == 'pages.profile' %}active{% endif %}"
                        style="text-align:right;" href="/profile/{{ current_user._id }}">Profile</a>
                    <a class="nav-item nav-link" style="text-align:right;"
                        href="{{ url_for('authorize.logout') }}">Logout</a>
                </div>
                {% else %}
                <div class="navbar-nav">
                    <a class="nav-item nav-link {% if request.endpoint == 'authorize.login' %}active{% endif %}"
                        style="text-align:right;" href="/login">Sign in</a>
                    <a class="nav-item nav-link {% if request.endpoint == 'authorize.register' %}active{% endif %}"
                        style="text-align:right;" href="/register">Register</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% endmacro %}