library/routes.py
from flask import Flask, render_template, Blueprint, request, session, flash, abort, redirect, url_for
from forms import ContactForm
from flask_login import login_required, current_user
from mail import Message, mail
from models import User, Profile
from db import db

pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


@pages.route("/")
def home():
    return render_template("home.html")


@pages.route("/appointment", methods=["GET", "POST"])
@login_required
def appointment():
    with open("templates/specs.txt", "r") as f:
        specs = f.readlines()
    return render_template("appointment.html", specs=specs)


@pages.route("/profile/<int:_id>", methods=["GET", "POST"])
@login_required
def profile(_id: int):
    if request.method == "GET":
        # profile_data = db.user.find_one({"_id": _id})
        profile_data = Profile.query.filter_by(_id=_id).first()
        if not profile_data:
            abort(404)
        # profile = User(**profile_data)
        _id = profile_data._id
        name = profile_data.name
        surname = profile_data.surname
        birthdate = profile_data.birthdate
        email = profile_data.email
        telephone = profile_data.telephone
        userid = profile_data.userid
        createdDate = profile_data.createdDate

        return render_template("profile.html", _id=_id, name=name, surname=surname, birthdate=birthdate, email=email, telephone=telephone, userid=userid, createdDate=createdDate)


@pages.route("/about")
def about():
    return render_template("about.html")


@pages.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()

    if request.method == "POST":
        if form.validate() == False:
            flash("All fields are required.")
            return render_template("contact.html", form=form)
        else:
            msg = Message(form.subject.data, sender="example@example.com",
                          recipients=["example@example.com"])
            msg.body = """ 
            From: %s &lt;%s&gt;
            %s 
            """ % (form.name.data, form.email.data, form.message.data)
            mail.send(msg)
            return "E-mail sent"
    elif request.method == "GET":
        return render_template("contact.html", form=form)

library/routes/doctor.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import login_required, current_user

from ..db.forms import EditRecommendation
from ..db.models import Appointment
from ..db.db import db


doctor = Blueprint(
    "doctor", __name__, template_folder="templates", static_folder="static"
)


@doctor.route("/create_app", methods=["GET", "POST"])
@login_required
def create_app():  # for doctors to create
    if current_user.isDoctor is False:
        flash("You are not authorized. Please log in as a doctor.", "danger")
        return redirect(url_for("pages.home"))

    if request.method == "POST":
        selected_date = request.form["selected_date"]
        selected_time = request.form["selected_time"]

        new_app = Appointment(
            app_date=selected_date,
            app_time=selected_time,
            availability=True,
            doctor_id=current_user._id,
        )

        db.session.add(new_app)
        db.session.commit()
        flash("Appointment slot created!")
        return render_template("doctor/create_app.html")
    return render_template("doctor/create_app.html")


@doctor.route("/edit_recommendation/<int:app_id>", methods=["GET", "POST"])
@login_required
def edit_recommendation(app_id: int):
    appointment = Appointment.query.get(app_id)
    form = EditRecommendation(obj=appointment)

    if appointment.doctor_id != current_user._id:
        flash("You are not authorized. Please log in as a doctor.", "danger")
        return redirect(url_for("pages.home"))

    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(appointment)
        db.session.commit()
        flash("Recommendation updated successfully.", "success")
        return redirect(url_for("pages.app_details", app_id=app_id))

    return render_template(
        "doctor/edit_recommendation.html", form=form, appointment=appointment
    )


@doctor.route("/delete_recommendations/<int:app_id>", methods=["GET", "POST"])
@login_required
def delete_recommendations(app_id: int):
    if request.method == "POST":
        appointment = Appointment.query.get_or_404(app_id)

        if appointment.doctor_id != current_user._id:
            flash("You are not authorized. Please log in as a doctor.", "danger")
            return redirect(url_for("pages.home"))
        else:
            appointment.recommendations = None
            db.session.commit()
            flash("Recommendations deleted successfully.", "success")

        return redirect(url_for("pages.app_details", app_id=app_id))
    else:
        return redirect(url_for("pages.app_details", app_id=app_id))

library/routes/routes.py
from flask import render_template, Blueprint, request, flash, abort, redirect, url_for
from flask_login import login_required, current_user

from ..db.forms import ContactForm, EditProfile, BookApp
from ..db.models import Profile, Specializations, Appointment, User
from ..db.db import db

from ..valid import calculate_age

import os
from dotenv import load_dotenv

import smtplib

load_dotenv()
EMAIL_TO = os.getenv("EMAIL_TO")
EMAIL_FROM = os.getenv("EMAIL_FROM")
SMTP = os.environ.get("SMTP")
PASSWORD = os.getenv("PASSWORD")


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


@pages.route("/", methods=["GET", "POST"])
def home():
    if request.method == "GET":
        booked_app = []
        appointment = []

        if current_user.is_authenticated:
            if current_user.isDoctor:
                appointment = Appointment.query.filter_by(
                    doctor_id=current_user._id
                ).all()

            elif current_user.isPatient:
                booked_app = Appointment.query.filter_by(
                    patient_id=current_user._id
                ).all()

        doctor_profiles = {}
        for app in appointment:
            doctor_profile = Profile.query.filter_by(userid=app.doctor_id).first()
            doctor_profiles[app.doctor_id] = doctor_profile

        if current_user.is_authenticated:
            display = Appointment.query.filter_by(patient_id=current_user._id).all()

            display_doctor = []
            for appointment in display:
                if appointment.doctor_id:
                    doctor_profile = Profile.query.filter_by(
                        userid=appointment.doctor_id
                    ).first()
                    display_doctor.append(doctor_profile)
                else:
                    display_doctor.append(None)

                return render_template(
                    "main/home.html",
                    booked_app=booked_app,
                    appointment=appointment,
                    doctor_profiles=doctor_profiles,
                    doctor_profile=doctor_profile,
                )

        else:
            display = []
            display_doctor = []

        return render_template(
            "main/home.html",
            booked_app=booked_app,
            appointment=appointment,
            doctor_profiles=doctor_profiles,
        )

    return render_template("main/home.html")


@pages.route("/appointment", methods=["GET", "POST"])
@login_required
def appointment():
    if request.method == "GET":
        specs = Specializations.query.all()
        return render_template("main/appointment.html", specs=specs)

    elif request.method == "POST":
        selected_specialization = request.form.get("specs")
        specs_id = Specializations.query.filter_by(
            specialization=selected_specialization
        ).first()

        if specs_id:
            appointments = (
                Appointment.query.join(User, Appointment.doctor_id == User._id)
                .filter(User.specs_id == specs_id._id, Appointment.availability == True)
                .all()
            )
        else:
            appointments = []

        return render_template(
            "main/appointment.html",
            specs=Specializations.query.all(),
            appointment=appointments,
            selected_specialization=selected_specialization,
        )


@pages.route("/app_details/<int:app_id>", methods=["GET", "POST"])
@login_required
def app_details(app_id: int):
    appointment = Appointment.query.filter_by(app_id=app_id).first()
    form = BookApp()

    if appointment.profile and appointment.profile.birthdate:
        patient_birthdate = appointment.profile.birthdate
        gender = appointment.profile.gender
    else:
        patient_birthdate = None
        gender = None

    if appointment.patient_id:
        age, month = calculate_age(patient_birthdate)
    else:
        age, month = None, None

    if not appointment:
        flash("Appointment not found.", "danger")
        return redirect(url_for("pages.appointment"))

    if request.method == "POST":
        if appointment.availability:
            appointment.availability = False
            appointment.patient_id = current_user._id
            db.session.commit()
            flash("Appointment booked successfully!", "success")
            return redirect(url_for("pages.app_details", app_id=app_id))

        appointment = Appointment.query.get_or_404(app_id)

        if appointment.doctor_id != current_user._id:
            flash("You are not authorized to submit recommendations.", "danger")
            return redirect(url_for("pages.app_details", app_id=app_id))

        recommendations = request.form.get("recommendations")
        appointment.recommendations = recommendations
        db.session.commit()

        flash("Recommendations submitted successfully!", "success")
        return redirect(
            url_for("pages.app_details", app_id=app_id, appointment=appointment)
        )

    if appointment.doctor_id:
        doctor_profile = Profile.query.filter_by(userid=appointment.doctor_id).first()
        user = User.query.get(appointment.doctor_id)
        if user:
            specialization = Specializations.query.get(user.specs_id)
        else:
            specialization = None
    else:
        doctor_profile = None

    return render_template(
        "main/app_details.html",
        appointment=appointment,
        form=form,
        doctor_profile=doctor_profile,
        specialization=specialization,
        age=age,
        month=month,
        gender=gender,
    )


@pages.route("/profile/<int:_id>", methods=["GET", "POST"])
@login_required
def profile(_id: int):
    if request.method == "GET":
        profile_data = Profile.query.filter_by(userid=_id).first()

        if not profile_data:
            abort(404)

        if not current_user.isAdmin:
            if current_user._id != _id:
                abort(403)

        return render_template("user/profile.html", profile_data=profile_data)


@pages.route("/edit_profile/<int:_id>", methods=["GET", "POST"])
@login_required
def edit_profile(_id: int):
    profile_data = Profile.query.filter_by(userid=_id).first()
    form = EditProfile(obj=profile_data)

    if current_user._id != _id:
        abort(403)

    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(profile_data)
        db.session.commit()
        flash("Profile updated successfully!", "success")
        return redirect(url_for("pages.profile", _id=_id))

    return render_template(
        "user/edit_profile.html", profile_data=profile_data, form=form
    )


@pages.route("/about")
def about():
    return render_template("main/about.html")


@pages.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()

    if request.method == "POST":
        if form.validate() == False:
            flash("All fields are required.")
            return render_template("main/contact.html", form=form)
        else:
            recipient = EMAIL_TO
            subject = form.subject.data
            sender = EMAIL_FROM
            message = f"""
            FROM: {form.name.data} <{form.email.data}>
            {form.body.data}
            """

            email_message = (
                f"Subject: {subject}\nFrom: {sender}\nTo: {recipient}\n\n{message}"
            )

            try:
                with smtplib.SMTP(SMTP, 587) as server:
                    server.starttls()
                    server.login(EMAIL_FROM, PASSWORD)
                    server.sendmail(sender, recipient, email_message)
                    server.close()
            except:
                print("-" * 30)
                print(email_message)
                print("-" * 30)

            return render_template("main/contact.html", success=True)
    elif request.method == "GET":
        return render_template("main/contact.html", form=form)


@pages.route("/deleteapp/<int:app_id>")
@login_required
def delete_app(app_id):
    appointment = Appointment.query.get_or_404(app_id)
    db.session.delete(appointment)
    db.session.commit()
    flash("Appointment deleted successfully.", "success")
    return redirect(request.referrer)  # redirects to current page


@pages.route("/deleteapp2/<int:app_id>")
@login_required
def delete_app_patient(app_id):
    appointment = Appointment.query.get_or_404(app_id)
    if appointment.patient_id == current_user._id:
        appointment.patient_id = None
        appointment.availability = True
        db.session.commit()
    flash("Appointment deleted successfully.", "success")
    return redirect(request.referrer)

library/templates/main/app_details.html
{% extends 'layout.html' %}

{% block head_content%}

{% endblock %}

{% block main_content %}

<div class="appointment_container">
  <h2>Appointment Details</h2>
  {% if current_user.isDoctor %}

  <dl>
    <dt>Date</dt>
    <dd>{{ appointment.app_date }}</dd>
    <dt>Time</dt>
    <dd>{{ appointment.app_time }}</dd>

    <dt>Patient</dt>
    {% if appointment.patient_id %}
    <td>{{ appointment.profile.name }}</td>
    <td>{{ appointment.profile.surname }}</td>
    <dt>Age</dt>
    {% if age is not none and month is not none %}
    <td> {{ age }} years and {{ month }} months old</td>
    {% else %}
    <td>Age information not available </td>
    {% endif %}
    <dt>Gender</dt>
    {% if gender %}
    <td> {{ gender }} </td>
    {% else %}
    <td>Gender information not available </td>
    {% endif %}
    {% else %}
    <dd>Patient information not available</dd>
    {% endif %}
  </dl>

  <div class="container">
    <section class="mt-4" style="text-align: center;">
      <h4>Recommendations</h4>
      {% if appointment.recommendations %}
      <div>
        <p>{{ appointment.recommendations }}</p>
        <div class="row">
          <div class="col-md-12">
            <form action="{{ url_for('doctor.edit_recommendation', app_id=appointment.app_id) }}" method="post">
              <button type="submit" class="btn btn-primary">Edit</button>
            </form>
            <form action="{{ url_for('doctor.delete_recommendations', app_id=appointment.app_id) }}" method="post">
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </div>
        </div>
        {% else %}
        <form action="{{ url_for('pages.app_details', app_id=appointment.app_id) }}" method="post">
          <div class="form-group">
            <label for="recommendations">Add Recommendations:</label>
            <textarea class="form-control" id="recommendations" name="recommendations" rows="4"
              style="width: 50%; margin: 0 auto;"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </section>
    {% endif%}
  </div>


  {% else %}

  <dl>
    <dt>Date</dt>
    <dd>{{ appointment.app_date }}</dd>
    <dt>Time</dt>
    <dd>{{ appointment.app_time }}</dd>

    {% if appointment.doctor_id %}
    <dt>Specialization</dt>
    {% if specialization %}
    <dd>{{ specialization.specialization }}</dd>
    {% else %}
    <dd>Specialization information not available</dd>
    {% endif %}

    <dt>Doctor</dt>
    {% if doctor_profile %}
    <dd>{{ doctor_profile.name }} {{ doctor_profile.surname }}</dd>
    {% else %}
    <dd>Doctor information not available</dd>
    {% endif %}
  </dl>

  {% if not appointment.availability %}

  <div class="container">
    <section class="mt-4" style="text-align: center;">
      <h4>Recommendations</h4>
      {% if appointment.recommendations %}
      <div class="recommendations">
        <p>{{ appointment.recommendations }}</p>
      </div>
      {% else %}
      <p> Currently, there are no recommendations available.</p>
      {% endif %}
    </section>
  </div>
  {% endif %}


  {% if appointment.availability %}
  <form method="post" action="{{ url_for('pages.app_details', app_id=appointment.app_id) }}">
    {{ form.hidden_tag() }}
    <button type="submit" class="btn btn-primary">Book Appointment</button>
  </form>
  {% endif %}
  {% endif %}
  {% endif %}

</div>
{% endblock %}

library/templates/main/appointment.html
{% extends 'layout.html' %}

{% block head_content%}

{% endblock %}

{% block main_content %}

{% if current_user.isDoctor %}

<p> Create empty appointment <a href="{{ url_for('doctor.create_app') }}">here</a>. </p>

{% else %}

<div class="appointment_container">
    <form action="{{ url_for('pages.appointment', app_id=_id)}}" method="post">
        <select name="specs" id="specs" class="form-select" aria-label="Default select example">
            <option selected> Please select specialization</option>
            {% for spec in specs %}
            <option value="{{ spec.specialization }}" class="dropdown-item">
                {{ spec.specialization }}
            </option>
            {% endfor %}
        </select>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
{% if appointment %}
<h3> Available Appointments for {{ selected_specialization }}: </h3>
<table class="table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        {% for app in appointment %}
        <tr>
            <td>{{ app.app_date }}</td>
            <td>{{ app.app_time }}</td>

            {% if app.availability %}
            <td><a href="{{ url_for('pages.app_details', app_id=app.app_id) }}" class="btn btn-primary">Details</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
{% if request.method == "POST" %}
<p>Currently, there are no available appointments.</p>
{% endif %}
{% endif %}
{% endif %}
{% endblock %}

library/templates/main/contact.html
{% extends 'layout.html' %}

{% block head_content %}

{% endblock %}

{% block main_content %}

<h3>
    In case you have any questions please feel free to contact us with the form below.
</h3>

{% if success %}
    <p> Thank you for your message! </p>
{% else %}

<form class="form-group" action="{{ url_for('pages.contact') }}" name="contact" method="post" novalidate>
    {{ form.hidden_tag() }}
    <dl>
        <dt> Name </dt>
        <dd> {{ form.name(class="formclass") }} </dd>
        <dt> E-mail address </dt>
        <dd> {{ form.email(class="formclass") }} </dd>
        <dt> Subject </dt>
        <dd> {{ form.subject(class="formclass") }} </dd>
        <dt> Message </dt>
        <dd> {{ form.body(class="form-control") }} </dd>
    </dl>
     {{ form.submit(class="btn btn-primary") }}
</form>
{% endif %}
{% endblock %}

library/templates/main/home.html
{% extends 'layout.html' %}

{% block head_content%}

{% endblock %}

{% block main_content %}

<h3>Welcome to MedCorp! How can we help you?</h3>
{% if current_user.isDoctor %}
<h4> For Doctors: </h4>
<a href="/appointment"> Create an appoinment </a>
<br>
{% elif current_user.isAdmin %}
<a href="/adminpanel"> Admin panel </a>
<br>
{% else %}
<h4> For Patients: </h4>
<a href="/appointment"> Make an appoinment </a>
<br>
{% endif %}


{% if current_user.isDoctor %}

    <h4>Appointments</h4>
    {% if appointment %}
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Patient Name</th>
                <th>Patient Surname</th>
                <th>Availability</th>
                <th>Delete</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            {% for app in appointment %}
            <tr>
                <td>{{ app.app_date }}</td>
                <td>{{ app.app_time }}</td>
                {% if app.patient_id %}
                <td>{{ app.profile.name }}</td>
                <td>{{ app.profile.surname }}</td>
                {% else %}
                <td>N/A</td>
                <td>N/A</td>
                {% endif %}
                <td>{{ "Available" if app.availability else "Booked" }}</td>
                <td> <a href="{{ url_for('pages.delete_app', app_id=app.app_id) }}" class="btn btn-danger"><i
                            class="fas fa-trash-alt"></i></a> </td>
                {% if not app.availability %}
                <td><a href="{{ url_for('pages.app_details', app_id=app.app_id) }}" class="btn btn-primary"><i class="fas fa-info-circle"></i> Details</a>
                </td>
                {% endif %}
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You have no appointments yet.</p>
    {% endif %}

{% elif current_user.isPatient %}

    <h4>Booked Appointments</h4>
    {% if booked_app %}
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Doctor Name</th>
                <th>Doctor Surname</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for app in booked_app %}
            <tr>
                <td>{{ app.app_date }}</td>
                <td>{{ app.app_time }}</td>
                {% if doctor_profile %}
                <td>{{ doctor_profile.name }}</td>
                <td>{{ doctor_profile.surname }}</td>
                {% else %}
                <td>Doctor information not available</td>
                <td>Doctor information not available</td>
                {% endif %}
                <td><a href="{{ url_for('pages.app_details', app_id=app.app_id) }}" class="btn btn-primary"><i class="fas fa-info-circle"></i> Details</a>
                </td>
                <td> <a href="{{ url_for('pages.delete_app_patient', app_id=app.app_id) }}" class="btn btn-danger"><i
                            class="fas fa-trash-alt"></i></a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You have not booked any appointments yet.</p>
    {% endif %}

{% else %}

{% endif %}


{% endblock %}